import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Stock Management System - CodeWithHarry",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-100">
        <div className="max-w-3xl mx-auto ">{children}</div>
      </body>
    </html>
  );
}
